import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { MarketplaceProviders, DynamicPricingCandyMachine } from "@strata-foundation/marketplace-ui";
import ReactShadow from "react-shadow/emotion";
import { usePublicKey } from "@strata-foundation/react";
import { useWalletModal, WalletDisconnectButton, WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { PublicKey } from '@solana/web3.js';

//import publicKey


const CandyMachine = () => {
  const { setVisible } = useWalletModal();
  const candyMachineIdPubkey = new PublicKey("GEEKi8uYrwb15Ea3rv2RMUBTnL8tvQKhC5xpJ1mkF82F");

  return (
  <div>
    <h2>This is the Strata Candy Machine</h2>
    <div className={styles.walletButtons}>
                    <WalletMultiButton />
                </div>
    <ReactShadow.div>
    <MarketplaceProviders resetCSS onError={(err) => console.error(err)}>
      <DynamicPricingCandyMachine candyMachineId={candyMachineIdPubkey} onConnectWallet={() => setVisible(true)} />
    </MarketplaceProviders>
    </ReactShadow.div>
  </div>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test Strata Toy App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CandyMachine/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
